/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packs;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sucharitha
 */
public class Login_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Login_Frame
     */
    public Login_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_add_sem = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jTextField_sem_name = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_add_sem_data = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField_dialog_name = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField_showGPA = new javax.swing.JTextField();
        jDialog_show_edit_sem = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jTextField_sem_name1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_show_sem_data = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jTextField_dialog_name1 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField_showGPA1 = new javax.swing.JTextField();
        card = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField1_password = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton_login = new javax.swing.JButton();
        jLabel3_loginresult = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        registerPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_uname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField_reg_pw = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField_reg_pw_cfm = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        dashboardPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_CGPA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_final = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_dash_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jDialog_add_sem.setMinimumSize(new java.awt.Dimension(431, 367));

        jLabel8.setText("Semester Title :");

        jButton10.setText("Save Data and Show GPA");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTable_add_sem_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Name", "Credits", "Grade Obtained"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_add_sem_data);
        if (jTable_add_sem_data.getColumnModel().getColumnCount() > 0) {
            jTable_add_sem_data.getColumnModel().getColumn(0).setResizable(false);
            jTable_add_sem_data.getColumnModel().getColumn(1).setResizable(false);
            jTable_add_sem_data.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel10.setText("Name:");

        jTextField_dialog_name.setEditable(false);

        jButton12.setText("Add Row");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Delete Row");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel15.setText("Calculated GPA:");

        jTextField_showGPA.setEditable(false);

        javax.swing.GroupLayout jDialog_add_semLayout = new javax.swing.GroupLayout(jDialog_add_sem.getContentPane());
        jDialog_add_sem.getContentPane().setLayout(jDialog_add_semLayout);
        jDialog_add_semLayout.setHorizontalGroup(
            jDialog_add_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_add_semLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDialog_add_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jDialog_add_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_sem_name)
                    .addComponent(jTextField_dialog_name, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jTextField_showGPA))
                .addGap(18, 18, 18)
                .addGroup(jDialog_add_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_add_semLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13))
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jDialog_add_semLayout.setVerticalGroup(
            jDialog_add_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_add_semLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jDialog_add_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_dialog_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addGroup(jDialog_add_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_add_semLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jDialog_add_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_sem_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jDialog_add_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField_showGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialog_add_semLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDialog_show_edit_sem.setMinimumSize(new java.awt.Dimension(431, 367));

        jLabel9.setText("Semester Title :");

        jTextField_sem_name1.setEditable(false);

        jButton11.setText("Save Data and Show GPA");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jTable_show_sem_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Credits", "Grade Obtained"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_show_sem_data);
        if (jTable_show_sem_data.getColumnModel().getColumnCount() > 0) {
            jTable_show_sem_data.getColumnModel().getColumn(0).setResizable(false);
            jTable_show_sem_data.getColumnModel().getColumn(1).setResizable(false);
            jTable_show_sem_data.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel12.setText("Name:");

        jTextField_dialog_name1.setEditable(false);

        jButton14.setText("Add Row");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Delete Row");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel16.setText("Calculated GPA:");

        jTextField_showGPA1.setEditable(false);

        javax.swing.GroupLayout jDialog_show_edit_semLayout = new javax.swing.GroupLayout(jDialog_show_edit_sem.getContentPane());
        jDialog_show_edit_sem.getContentPane().setLayout(jDialog_show_edit_semLayout);
        jDialog_show_edit_semLayout.setHorizontalGroup(
            jDialog_show_edit_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_show_edit_semLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDialog_show_edit_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jDialog_show_edit_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_sem_name1)
                    .addComponent(jTextField_dialog_name1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jTextField_showGPA1))
                .addGroup(jDialog_show_edit_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_show_edit_semLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15)
                        .addContainerGap())
                    .addGroup(jDialog_show_edit_semLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jDialog_show_edit_semLayout.setVerticalGroup(
            jDialog_show_edit_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_show_edit_semLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jDialog_show_edit_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_dialog_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addGroup(jDialog_show_edit_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_show_edit_semLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jDialog_show_edit_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_sem_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jDialog_show_edit_semLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField_showGPA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialog_show_edit_semLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        card.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("username:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("password:");

        jTextField_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPasswordField1_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField1_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1_passwordActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("Show / Hide");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton_login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_login.setText("login");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        jLabel3_loginresult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3_loginresult.setText("Login Status");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginPanelLayout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(loginPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel3_loginresult, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jPasswordField1_password, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(jCheckBox1))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_loginresult)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
        );

        card.add(loginPanel, "loginCard");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("username:");

        jTextField_uname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("password:");

        jPasswordField_reg_pw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("confirm password:");

        jPasswordField_reg_pw_cfm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("check for availability");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Name:");

        jTextField_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField_reg_pw_cfm, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jPasswordField_reg_pw)
                            .addComponent(jTextField_name)
                            .addComponent(jTextField_uname))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField_reg_pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField_reg_pw_cfm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        card.add(registerPanel, "registerCard");

        jLabel6.setText("Cumulative GPA :");

        jTextField_CGPA.setEditable(false);

        jTable_final.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sem Name", "GPA obtained", "Credits Taken"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_final);

        jButton6.setText("Show/ Edit Sem Data");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Delete Sem Data");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Add Sem Data");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Refresh Table and Update CGPA");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel7.setText("Name: ");

        jTextField_dash_name.setEditable(false);
        jTextField_dash_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_dash_nameActionPerformed(evt);
            }
        });

        jButton1.setText("logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_CGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_dash_name, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_dash_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_CGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        card.add(dashboardPanel, "dashCard");

        getContentPane().add(card, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // TODO add your handling code here:
    
    Connection connection = null;
    PreparedStatement ps;
    String current_uname = new String("");
    String current_pw = new String("");
    try {
        connection = DriverManager.getConnection("jdbc:mysql://localhost/gpa_database","root","");
        ps = connection.prepareStatement("SELECT `username`, `password` FROM `login_table` WHERE `username` = ? AND `password`= ?");
        ps.setString(1, jTextField_username.getText());
        ps.setString(2, String.valueOf(jPasswordField1_password.getPassword()));            
        current_uname = jTextField_username.getText();
        current_pw = new String (jPasswordField1_password.getPassword());
        ResultSet result = ps.executeQuery();
        if (result.next())
        {
            jLabel3_loginresult.setText("login successful");
            CardLayout c1=(CardLayout)card.getLayout();
            c1.show(card,"dashCard");
            jTextField_dash_name.setText(current_uname);
        }
        else
        {
            jLabel3_loginresult.setText("Invalid credentials");
            JOptionPane.showMessageDialog(null,"INVALID CREDENTIALS","TITLE",JOptionPane.WARNING_MESSAGE);
        }
    } catch (SQLException ex) {
        Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
    }
    finally
    {
        try {            
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    jTextField_username.setText("");
    jPasswordField1_password.setText("");
    CardLayout c1=(CardLayout)card.getLayout();
    c1.show(card,"registerCard");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    Connection connection = null;
    String un = jTextField_uname.getText();
    String n = jTextField_name.getText();
    char[] p = jPasswordField_reg_pw.getPassword();
    String pw = new String(p);
    boolean flag = false;
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/gpa_database","root","");
            Statement sta = connection.createStatement();
            int a = sta.executeUpdate("INSERT INTO registration_table(username, name,password) VALUES ('"+un+"','"+n+"','"+pw+"')");
            //TODO: convert pw char[] into a string and pass it as parameter.
        }
        catch (SQLException ex) {
            Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
            flag = true;
        }
        finally {
            if (flag){
                //TODO: display error dialog and message
            }
            else {
                JOptionPane.showMessageDialog(null,"REGISTRATION SUCCESSFUL","TITLE",JOptionPane.WARNING_MESSAGE);
                //TODO: display ok dialog and message
                //TODO: Check Availability button functionality.
            }
            try {            
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    CardLayout c1=(CardLayout)card.getLayout();
    c1.show(card,"loginCard");
    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    if(jCheckBox1.isSelected()){
        jPasswordField1_password.setEchoChar((char)0);
    }
    else{
        jPasswordField1_password.setEchoChar('*');
    }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jDialog_add_sem.setVisible(true);
        jTextField_sem_name.setText("");
        jTextField_showGPA.setText("");
        DefaultTableModel tb1 = (DefaultTableModel)jTable_add_sem_data.getModel();
        int no_rows = jTable_add_sem_data.getRowCount();
        if (no_rows> 0) {
            for (int i = no_rows-1; i >= 0; i--) {
                tb1.removeRow(i);
            }
        }
        String current_name = new String(jTextField_dash_name.getText());
        jTextField_dialog_name.setText(current_name);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField_username.setText("");
        jPasswordField1_password.setText("");
        CardLayout c1=(CardLayout)card.getLayout();
        c1.show(card,"loginCard");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1 = (DefaultTableModel)jTable_add_sem_data.getModel();
        Object[] row = {"",null,null};
        tb1.addRow(row);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1 = (DefaultTableModel)jTable_add_sem_data.getModel();
        int[] selectedRows = jTable_add_sem_data.getSelectedRows();
        if (selectedRows.length > 0) {
            for (int i = selectedRows.length - 1; i >= 0; i--) {
                tb1.removeRow(selectedRows[i]);
            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         
        Connection connection = null;
        PreparedStatement ps;
        String name = jTextField_dialog_name.getText();
        String tablename = jTextField_sem_name.getText()+"_"+name;
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/gpa_database","root","");
            connection.setAutoCommit(false);
            while(jTable_final.getRowCount() > 0) 
            {
                ((DefaultTableModel) jTable_final.getModel()).removeRow(0);
            }
            Statement sta = connection.createStatement();
            int a = sta.executeUpdate("CREATE TABLE IF NOT EXISTS "+tablename+" (CourseName varchar(255) ,Credits int, GradeOb int)");
            System.out.println("after creating new table. check in db now");
            //TODO: if table name pair exists, ask to change name
            //TODO: if table name exists, ask to change name
            DefaultTableModel tb1 = (DefaultTableModel)jTable_add_sem_data.getModel();
            int no_rows = tb1.getRowCount();
            int denom_int =0;
            for (int row = 0; row < no_rows; row++){
            
                int cred = (int)tb1.getValueAt(row, 1);
                denom_int += cred;
            }
            //TODO: Avoid repetitive statements in usertableslist
            Statement sta3 = connection.createStatement();
            int a3 = sta3.executeUpdate("DELETE FROM "+tablename+"");
            String update_table = "INSERT INTO "+tablename+"(CourseName,Credits,GradeOb) VALUES(?,?,?)";
            PreparedStatement pst = connection.prepareStatement(update_table);
            float num= 0;
            float denom =0;
            for (int row = 0; row < no_rows; row++){
            
                String cname = (String)tb1.getValueAt(row, 0);
                float cred = (int)tb1.getValueAt(row, 1);
                float gradeOb = (int)tb1.getValueAt(row, 2);
                num += cred*gradeOb;
                denom += cred;
                pst.setString(1, cname);
                pst.setFloat(2, cred);
                pst.setFloat(3, gradeOb);
                
                pst.addBatch();
            }
            float semgpa = num/denom;
            Statement sta4 = connection.createStatement();
            int b = sta4.executeUpdate("DELETE FROM usertableslist WHERE name ='"+name+"' AND sem_table_name ='"+tablename+"' ");
            Statement sta2 = connection.createStatement();
            int a2 = sta2.executeUpdate("INSERT INTO usertableslist(name,sem_table_name,total_credits,gpa) VALUES ('"+name+"','"+tablename+"','"+denom_int+"','"+semgpa+"')");
            pst.executeBatch();
            connection.commit();
            System.out.println(num/denom);
            DecimalFormat dc = new DecimalFormat("0.00");
            String GPA = dc.format(num/denom);
            jTextField_showGPA.setText(GPA);
            System.out.println("debug ");
            System.out.println(denom_int);
            //TODO: check if table is created properly, otherwise display error.
        } catch (SQLException ex) {
            Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            try {            
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jPasswordField1_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1_passwordActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1 = (DefaultTableModel)jTable_final.getModel();
        DefaultTableModel tb2 = (DefaultTableModel)jTable_show_sem_data.getModel();
        int[] selectedRows = jTable_final.getSelectedRows();
        int rowCount = tb2.getRowCount();
        //TODO: Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            tb2.removeRow(i);
        }
        String sem_name = "";
        String name = jTextField_dash_name.getText();
        if (selectedRows.length>1){
            JOptionPane.showMessageDialog(null,"Please select only 1 row","Warning",JOptionPane.WARNING_MESSAGE);
            jTable_final.clearSelection();
        }
        else {
            Connection connection = null;
            int row_index = jTable_final.getSelectedRow();
            if (row_index == -1){
                JOptionPane.showMessageDialog(null,"Please select atleast 1 row","Warning",JOptionPane.WARNING_MESSAGE);
            }
            else{
                jDialog_show_edit_sem.setVisible(true);
                sem_name = (String)jTable_final.getValueAt(row_index,0);
                String subsemname = sem_name.substring(0, sem_name.length() - name.length() -1);
                jTextField_sem_name1.setText(subsemname);                
                try {
                    connection = DriverManager.getConnection("jdbc:mysql://localhost/gpa_database","root","");
                    Statement sta = connection.createStatement();
                    ResultSet rs = sta.executeQuery("SELECT gpa FROM usertableslist WHERE name ='"+name+"' AND sem_table_name = '"+sem_name+"'");
                    //TODO: if show is pressed before refresh table, dont do it.
                    while (rs.next()){
                        float a = rs.getFloat("gpa");
                        DecimalFormat dc = new DecimalFormat("0.00");
                        String GPA = dc.format(a);
                        jTextField_dialog_name1.setText(name);
                        jTextField_showGPA1.setText(GPA);
                    }
                    System.out.println("d1");
                    Statement sta2 = connection.createStatement();
                    System.out.println(sem_name);
                    ResultSet rs2 = sta2.executeQuery("SELECT CourseName,Credits,GradeOb FROM "+sem_name+"");
//                    System.out.println("d2");
                    while (rs2.next()){
//                        System.out.println("d3");
                        String semname = rs2.getString("CourseName");
                        int creds = rs2.getInt("Credits");
                        float gradeob = rs2.getFloat("GradeOb");
                        tb2.addRow(new Object[]{semname, creds, gradeob});
                    }
                    jTable_show_sem_data.setModel(tb2);              
                }
                catch(SQLException e){
                    Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, e);

                }
                finally{
                    try {  
                        connection.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }   
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Connection conn = null;
        PreparedStatement ps;
        String name = jTextField_dialog_name1.getText();
        String tablename = jTextField_sem_name1.getText()+"_"+name;
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost/gpa_database","root","");
            conn.setAutoCommit(false);
            Statement sta = conn.createStatement();
            DefaultTableModel tb1 = (DefaultTableModel)jTable_show_sem_data.getModel();
            int no_rows = tb1.getRowCount();
            int denom_int =0;
            for (int row = 0; row < no_rows; row++){
                int cred = (int)tb1.getValueAt(row, 1);
                denom_int += cred;
            }
            Statement sta3 = conn.createStatement();
            int a3 = sta3.executeUpdate("DELETE FROM "+tablename+"");
            String update_table = "INSERT INTO "+tablename+"(CourseName,Credits,GradeOb) VALUES(?,?,?)";
            PreparedStatement pst = conn.prepareStatement(update_table);
            float num= 0;
            float denom =0;
            for (int row = 0; row < no_rows; row++){
            
                String cname = (String)tb1.getValueAt(row, 0);
                float cred = (int)tb1.getValueAt(row, 1);
                float gradeOb = (float)tb1.getValueAt(row, 2);
                num += cred*gradeOb;
                denom += cred;
                pst.setString(1, cname);
                pst.setFloat(2, cred);
                pst.setFloat(3, gradeOb);
                
                pst.addBatch();
            }
            float semgpa = num/denom;
            Statement sta4 = conn.createStatement();
            int b = sta4.executeUpdate("DELETE FROM usertableslist WHERE name ='"+name+"' AND sem_table_name ='"+tablename+"' ");
            Statement sta2 = conn.createStatement();
            int a2 = sta2.executeUpdate("INSERT INTO usertableslist(name,sem_table_name,total_credits,gpa) VALUES ('"+name+"','"+tablename+"','"+denom_int+"','"+semgpa+"')");
            pst.executeBatch();
            conn.commit();
            System.out.println(num/denom);
            DecimalFormat dc = new DecimalFormat("0.00");
            String GPA = dc.format(num/denom);
            jTextField_showGPA1.setText(GPA);
            System.out.println("edit data working");
            //TODO: check if table is created properly, otherwise display error.
        }
        catch (SQLException e){
            Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, e);
        }
        finally{
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        
        DefaultTableModel tb1 = (DefaultTableModel)jTable_show_sem_data.getModel();
        Object[] row = {"",null,null};
        tb1.addRow(row);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        
        DefaultTableModel tb1 = (DefaultTableModel)jTable_show_sem_data.getModel();
        int[] selectedRows = jTable_show_sem_data.getSelectedRows();
        if (selectedRows.length > 0) {
            for (int i = selectedRows.length - 1; i >= 0; i--) {
                tb1.removeRow(selectedRows[i]);
            }
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Connection connection = null;
        PreparedStatement ps;
        String name = jTextField_dash_name.getText();
        String end = "_"+name;
        //TODO: Name slicing to remove _admin.
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/gpa_database","root","");
            connection.setAutoCommit(false);
            Statement sta2 = connection.createStatement();
            //TODO: Insert into table from database
            while(jTable_final.getRowCount() > 0) 
            {
                ((DefaultTableModel) jTable_final.getModel()).removeRow(0);
            }
            DefaultTableModel tb1 = (DefaultTableModel)jTable_final.getModel();
            String sql_get_data = "SELECT name,sem_table_name,total_credits,gpa FROM usertableslist WHERE name = '"+name+"' AND sem_table_name LIKE '%"+end+"' ";
            ResultSet rs = sta2.executeQuery(sql_get_data);
            while(rs.next())
            {
                String semname = rs.getString("sem_table_name");
                int creds = rs.getInt("total_credits");
                Float gpa = rs.getFloat("gpa");
                tb1.addRow(new Object[]{semname, gpa, creds});
            }
            System.out.println("working");
            jTable_final.setModel(tb1);
            int no_rows = jTable_final.getRowCount();
            float num= 0;
            float denom =0;
            for (int row = 0; row < no_rows; row++){
            
                float cred = (int)tb1.getValueAt(row, 2);
                float gradeOb = (float)tb1.getValueAt(row, 1);
                num += cred*gradeOb;
                denom += cred;
            }
            float cgpa = num/denom;
            DecimalFormat dc = new DecimalFormat("0.00");
            String CGPA = dc.format(cgpa);
            jTextField_CGPA.setText(CGPA);
        } catch (SQLException ex) {
            Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            try {            
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        Connection connection = null;
        PreparedStatement ps;
        String uname = jTextField_dash_name.getText();
        String tablename = "";
        DefaultTableModel tb1 = (DefaultTableModel)jTable_final.getModel();
        int[] selectedRows = jTable_final.getSelectedRows();
        if (selectedRows.length > 1) {
            JOptionPane.showMessageDialog(null,"Select only one row at a time","TITLE",JOptionPane.WARNING_MESSAGE);
            jTable_final.clearSelection();
        }     
        else{
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost/gpa_database","root","");
                Statement sta = connection.createStatement();
                int row_index = jTable_final.getSelectedRow();
                String sem_name = (String)jTable_final.getValueAt(row_index, 0);
                System.out.println(sem_name);
                int a = sta.executeUpdate("DELETE FROM usertableslist WHERE name ='"+uname+"' AND sem_table_name = '"+sem_name+"' ");
//                if (selectedRows.length > 0) {
//                    for (int i = selectedRows.length - 1; i >= 0; i--) {
//                        tb1.removeRow(selectedRows[i]);
//                    }
//                }
                System.out.println("deleted selected table");
//                Statement sta1 = connection.createStatement();
//                int b = sta1.executeUpdate("DROP TABLE sem4_admin ");
//                System.out.println(+ "111");
                }   
            catch (SQLException e){
                System.out.println(e);
            }
            finally {
                try {
                    connection.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField_dash_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_dash_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_dash_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel card;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_login;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDialog jDialog_add_sem;
    private javax.swing.JDialog jDialog_show_edit_sem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_loginresult;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1_password;
    private javax.swing.JPasswordField jPasswordField_reg_pw;
    private javax.swing.JPasswordField jPasswordField_reg_pw_cfm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_add_sem_data;
    private javax.swing.JTable jTable_final;
    private javax.swing.JTable jTable_show_sem_data;
    private javax.swing.JTextField jTextField_CGPA;
    private javax.swing.JTextField jTextField_dash_name;
    private javax.swing.JTextField jTextField_dialog_name;
    private javax.swing.JTextField jTextField_dialog_name1;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_sem_name;
    private javax.swing.JTextField jTextField_sem_name1;
    private javax.swing.JTextField jTextField_showGPA;
    private javax.swing.JTextField jTextField_showGPA1;
    private javax.swing.JTextField jTextField_uname;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel registerPanel;
    // End of variables declaration//GEN-END:variables
}
